### ISSUE TITLE
Passing arguments to a composed factory and how to break up a classical inheritance architecture

### ISSUE THREAD

**Issue by meandmax** [ericelliott/stampit#45]
Hey Eric,

I was thinking about how you would recommend passing arguments to composed factories and came up with the following approach:

```js
var stampit = require('stampit');

var defaults = stampit().state({
    name: 'Max',
    link: '/',
    obj: {mine: 'mine'},
    node: {myNode: 'myNode'}
});

var a = stampit().enclose(function () {
    var a = 'a';

    this.getA = function () {
        return a;
    };
});

var b = stampit().enclose(function () {
    var b = 'b';

    this.getB = function () {
        return b;
    };
});

var factory = stampit().compose(a, b, defaults);
var c       = factory();

var link = '/beer';
var obj  = {other: 'other'};
var node = {otherNode: 'otherNode'};

// change default state by creating instance an overwriting defaults
var d = factory({
    link: link,
    obj: obj,
    node: node
});
```

With this approach, I set all properties at the beginning and compose it into my new factory. When I create a new instance (d) I just overwrite the defaults.

Is this the way to do something like this? Any recommendations?

Would be very nice to have a simple example in the docs to see how to break up a classical inheritance/constructor pattern with your approach. At the moment I`m trying to figure out how to break up a CoffeeScript/Bacon.js architecture with classical inheritance and use object composition (stampit) instead.

How would you implement something like this in plain JavaScript + stampit?

```CoffeeScript
class A
    constructor: (a, b, c) ->
        console.log(a)

    funcA: () ->
        return 'funcA'

class B extends A
    constructor: (a, b, c) ->
        super
        console.log(b)

    funcB: () ->
        return 'funcB'

class C extends A
    constructor: (a, b, c) ->
        super
        console.log(c)
        console.log(@funcA())
        console.log(@funcC())

    funcC: () ->
        return 'funcC'

new C('a', 'b', 'c')
```

I like the flexibility which object-composition (stampit) gives me though ... ;-)

Thanks, Max

**Comment by ericelliott** [comment]
> Is this the way to do something like this? Any recommendations?

Yes, I write code like that frequently.

> How would you implement something like this in plain JavaScript + stampit?

You don't. [Super](http://en.wikipedia.org/wiki/Call_super) is [a code smell](http://martinfowler.com/bliki/CallSuper.html). Any use of super tightly couples the child class to the parent class, which creates brittle code.

Instead, flatten the hierarchy and use the same defaults / overrides pattern you listed above. That way, `A`, `B`, and `C` could all inherit from a common base, and you won't create super chains like you would if you had `C` inheriting from `B` instead of `A`.

See also [The Two Pillars of JavaScript Pt 1](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3).

**Comment by ericelliott** [comment]
About argument passing... the pattern I recommend is to create setter methods that are semantically named for the particular stamp the arguments are intended for.

Stampit does support argument passing, but due to the potential conflicts in composed stamps, I consider any arguments outside the ones that set properties on the object to be an anti-pattern.

**Comment by meandmax** [comment]
I`m about to refactor lots of old classes written in CoffeeScript by translate them in pure JavaScript and using stampit for object composition instead of classical inheritance. Your answer is exactly what I was hoping to hear, just wasn´t sure if I´m still on track.

About argument passing:

```js
var d = factory({
    link: link,
    obj: obj,
    node: node
});
```
... for setting public properties to something different then defaults, right?

```js
var b = stampit().enclose(function () {
    var b = 'b';

    this.setB = function(val) {
        b = val;
    };

    this.getB = function () {
        return b;
    };
});
```
... and something like this for setting private properties, right?

This is so much fun, think I got it ;-).!

I will let you know how it goes with the refactoring.

Thanks so much, cheers Max

**Comment by koresar** [comment]
The approach Eric does not recommend looks like this:
```js
var stamp = stampit().enclose(function (arg1, arg2) {
  var privateArg1 = arg1;
  var privateArg2 = arg2;
  // your code
});

var obj = stamp(yourPublicState, yourPrivateArg1, yourPrivateArg2);
```

I would not recommend this either unless you are confident there will be no conflicts across multiple enclosures.
