### ISSUE TITLE
Where to best put "abstract" method and possibilities for "protected" members feature

### ISSUE THREAD

**Issue by dwiyatci** [ericelliott/stampit#53]
Hi @ericelliott,

first off, please let me express my gratitude for your brilliant work on this stampit library and your enlightenment on JS in general — it has changed the way I code JavaScript, for *good*. :smiley_cat: I've been starting using stampit in my project for a couple of weeks now, and I'm feeling so cool about it.

That said, there are two things that I'm still not sure of:

**1. Should I put "abstract" method in the delegate prototype (`methods`) or in the closure (`enclose`) of the "abstract" stamp?**

```javascript
/*
 * Abstract .foo() method in the delegate prototype.
 */
var abstractStamp1 = stampit()
    .methods({
        foo: function () {
            throw new Error('.foo() not implemented.');
        }
    });

/*
 * Abstract .foo() method in the closure.
 */
var abstractStamp2 = stampit()
    .enclose(function () {
        stampit.mixIn(this, {
            foo: function () {
                throw new Error('.foo() not implemented.');
            }
        })
    });

/*
 * Concrete .foo() method in the privileged area,
 * with the need of accessing private `bar` property.
 */
var concreteStamp = stampit()
    .enclose(function () {
        var bar = 'bar';

        stampit.mixIn(this, {
            foo: function () {
                bar = bar + 'foo';
                return bar;
            }
        })
    });

/*
 * Which one is better? 
 */
var objStamp1 = abstractStamp1.compose(concreteStamp);
var objStamp2 = abstractStamp2.compose(concreteStamp);
```
**2. Are there possibilities to express "protected" members in JS by using stampit or is it also considered as an anti-pattern? Any suggestions for alternative?**

```javascript
var abstractStamp = stampit()
    .enclose(function () {
        var foo = 'foo';

        stampit.mixIn(this, {
            getFoo: function () {
                return foo;
            }
        })
    });


var concreteStamp = stampit()
    .enclose(function () {
        var bar = 'bar';

        stampit.mixIn(this, {
            getFooBar: function () {
                // Use getter method to access `foo` property of the `abstractStamp`.
                return this.getFoo() + bar;
            }
        })
    });

var obj = abstractStamp.compose(concreteStamp).create();

/*
 * Supposed-to-be-protected `foo` property,
 * yet it is now exposed to the world.
 * And I'm not quite satisfied about it :/
 */
obj.getFoo();  // "foo"
```
Prost! :beers:

**Comment by ericelliott** [comment]
Thanks!

## Abstract

I don't create a lot of abstract stamps. Instead, I'll create a stamp that cranks out fully functioning instances that have sensible default behaviors. I have still created abstract stamps once in a while, when I really needed to throw an error if the inheriting stamp fails to override something.


## Delegate or .enclose()

If you need data privacy, you really don't have a choice. You must use `.enclose()`.

For methods that can use `this` and store public state, you may prefer to delegate with `.methods()`, because it will save a little memory. But let's be honest --  memory isn't really a big bottleneck for most use cases these days. Encapsulation may take priority for you.


## Protected is an anti-pattern

In other languages, **protected** means that the member can be accessed from both the class itself, and the class descendants, but not from other functions outside the class.

**Protected** members are an anti-pattern because they allow tight coupling between a child class and it's parent. Protected members are not possible with Stampit, and that is a good thing. If you need to share state with descendants, use modules to share access (make both abstract and descendants depend on a module that exports the private stuff you want to share between them).
