### ISSUE TITLE
react components with stamps

### ISSUE THREAD

**Issue by troutowicz** [ericelliott/stampit#66]
Just opening this for discussion. I am currently porting my [app](https://github.com/troutowicz/geoshare/tree/stamps) from ES6 classes to stamps, and was wondering if anyone else has thought of doing the same.

So far, I have ran into a couple issues, related to [childContextTypes](https://github.com/facebook/react/pull/3940) and component [testing](https://github.com/facebook/react/pull/3941).

**Comment by ericelliott** [comment]
Hi @troutowicz, I'm definitely planning to use Stampit heavily for React components. I was initially thinking I would write a reusable stamp specifically designed to create React components, but now that I've been thinking deeper about it for a while, I'm thinking that some features of React components also make a lot of sense to support natively in Stampit. For instance, the `propTypes` that I've already mentioned in a couple other threads today.

For the people not following those discussions yet, those threads are:

* https://github.com/ericelliott/stampit/issues/67 and
* https://github.com/ericelliott/stampit/issues/64

I will probably still create a specialized stamp for React, but that would be implemented in its own module that requires Stampit.

I'm really glad you're already working on a React app with Stampit. I'm just beginning work on my first attempt. I wanted to take some time working with React directly in order to get a sense of which features are most important to support, and the most natural place to implement those features.

We should use this thread to connect about our findings, and the problems we need to solve for React users going forward.

Just keep in mind, Stampit is in production use in a lot of apps that don't use React, so anything that is React-specific rather than generally usable, we won't be adding those to React. I've created a separate repo for the React stamp project, but there's nothing there yet.

If you're working on something similar, please create a GitHub repo for it, and we can potentially merge our work.

**Comment by troutowicz** [comment]
I'll put together a repo in a bit.

**Comment by ericelliott** [comment]
For those who aren't aware, you don't need `class` to use React, even if you don't use the deprecated `.createComponent()` method: https://gist.github.com/jquense/47bbd2613e0b03d7e51c

In this thread, we're discussing ways we can improve the experience of building React components using composable stamps, and it will likely result in a specialized library that sugars react component creation and composition.

Not sure what we mean by composition? You could compare it to using React mixins that `.createComponent()` enables, except that you can compose them without referencing the components you inherit from inside the new component declaration.

**Comment by ericelliott** [comment]
> I'll put together a repo in a bit.

:+1:

**Comment by troutowicz** [comment]
@ericelliott [react-stamp](https://github.com/troutowicz/react-stamp)

**Comment by ericelliott** [comment]
It's a start. I made mine a factory that takes React as a parameter and uses stampit internally so that the user is never exposed directly to Stampit, for a couple reasons:

1. Having multiple instances of React on the same page can cause a lot of problems. For instance, you can get errors if you try to use refs, and I imagine it would probably screw with context and some of the internal React type checking as well.
2. You can focus on exporting an ideal API to create React components.

**Comment by troutowicz** [comment]
I started thinking of abstracting stampit as I created the repo. I just wanted to get something basic put together while we discuss. I'll start making these changes when I'm back at a computer.

**Comment by ericelliott** [comment]
:+1:

**Comment by troutowicz** [comment]
@ericelliott So I'm thinking of an API that's somewhat analogous to React.createClass.

```js
import react from 'react';
import stampit from 'react-stampit';

export default stampit(react, {
  mixins: { },

  statics: { },

  // lifecycle methods
  render() { }
});
```

Thoughts?

**Comment by ericelliott** [comment]
I had a similar thought, but I think it should have `propTypes` for convenience, which gets set as a static.

**Comment by ericelliott** [comment]
Also, I'm not a fan of passing in mixins. I'd prefer it to offer a `.compose()` method like Stampit does.

**Comment by troutowicz** [comment]
Sure thing.

**Comment by troutowicz** [comment]
@ericelliott I reworked the library, take a look :)

**Comment by troutowicz** [comment]
Let's continue discussion [here](https://github.com/troutowicz/react-stampit/issues/1).

**Comment by troutowicz** [comment]
@ericelliott Thanks for the mention on your social media profiles!

**Comment by ericelliott** [comment]
=)

**Comment by koresar** [comment]
To follow the discussion follow the link: https://github.com/troutowicz/react-stampit/issues/1

Closing this issue as irrelevant.
